#namespace: bcs
name: "bcs.bcsping"
version: '0.0.1'
authors: ['i disown this']
description: i blatant copy and rename of the ping module
license: GPL-2.0-or-later
#tags:
#    - bad
#    - breaks
#    - dontuse
#    - stayaway
#repository: http://github.com/bcoca/bcsping
