namespace: bcs
name: "bcsping"
version: '0.1'
authors: ['i disown this']
description: i blatant copy and rename of the ping module
license: dont use, this is for a test
tags:
    - bad
    - breaks
    - dontuse
    - stayaway
repository: github.com/bcoca/bcsping
